package dev.paulshields.aoc.year2025

import assertk.assertThat
import assertk.assertions.isEqualTo
import org.junit.jupiter.api.Test

class Day7Test {
    @Test
    fun `should pass provided test for day 7 part 1`() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().lines()

        val result = countTachyonBeamSplits(input)

        assertThat(result).isEqualTo(21)
    }

    @Test
    fun `should pass provided test for day 7 part 2`() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().lines()

        val result = countTachyonParticleTimelines(input)

        assertThat(result).isEqualTo(40)
    }
}
